### ISSUE TITLE
Possible Issues with Compiling for Bambino 210e

### ISSUE THREAD

**Issue by kasandell** [Smoothieware/Smoothie2#12]
I've been trying to get the Smoothie2 source to run on the bambino 210e for about the past 2-3 weeks with no luck. The first sign of an issue is when making gcc4mbed, the compilation of the sample programs fail with the error 
No rule to make target "../../external/mbed/libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_8_0_0/s110_nrf51822_8.0.0_softdevice.hex". 
However, I can still use BuildShell after the failed compilation. 
I'm not sure how much this has to do with gcc4mbed but when following the instructions in Smoothie2Notes on how to flash over USB bootloader, the only available memory is SPIFI, so there is no bank A or B available to flash. After flashing the code to SPIFI through lpcscrypt, there is no communication between my computer and the board. This made me think that something in either gcc4mbed or Smoothie2 might not be right for executing from SPIFI. I do know, however, that the board is functioning and able to run code properly from SPIFI, because I have loaded sample programs from dfusec onto the board, and they have run. I also know that my usb ports are not malfunctioning because I've hooked up my old Azteeg x5 mini and it communicates fine.
The only reason I can think of that this is happening is that the gcc4mbed support for the lpc4330(bambino processor) is possibly only good for the lpc4337(smoothie2 board).

Many thanks in advance for any help.

P.S. I forgot to mention I'm running all of this on my mac air running OSX 10.11. I have also tried the ISP loading technique from your notes, but it failed to load code onto the bambino.

**Comment by adamgreen** [comment]
- Comment out the following line in src/makefile so that it will build for the memory model on your LPC4330 instead of the LPC4337 in the Smoothie2 board.

`LPC4330_M4_LSCRIPT := LPC4337.ld`
- When using LPCScrypt to program your device, you will want to change the second LPCScrypt command to be the following instead so that it uses SPIFI instead of internal FLASH:

`/Applications/lpcscrypt_1.6.0_652/bin/lpcscrypt program +c LPC4330_M4/Smoothie2.bin SPIFI`

Hopefully that will get you further along. There will no doubt be some other differences that you have to deal with.

**Comment by arthurwolf** [comment]
Thanks @adamgreen :)

**Comment by adamgreen** [comment]
@kasandell Did you have a chance to try the changes I mentioned above? Did you get any further?

**Comment by kasandell** [comment]
Hey @adamgreen so sorry. I haven't had wifi for the past few days so I just saw this. When I posted this, I was hoping to get the board working before I left for Europe but I didn't get a reply until I was in the airport. Sadly I won't be able to test this for another 2 weeks. I do apologize for this.

**Comment by adamgreen** [comment]
@kasandell Ok. Keep us posted after you get back and have time to experiment with it again.

**Comment by kasandell** [comment]
Hey @adamgreen. I just got back from Europe, and testing smoothie out with the new suggestions, nothing seems to behave any different than it did before. Any ideas on what else to try?

**Comment by adamgreen** [comment]
Nothing else comes to mind. I have a Bambino 210E here that I can try on sometime later this week.

**Comment by kasandell** [comment]
Alright. I'll try out some other operating systems and see if my mac is just causing problems.

**Comment by adamgreen** [comment]
If I get it to work later this week, it will be on OS X since that is my primary OS and is what I have used for all Smoothie2 work so far :) I believe that Arthur uses Ubuntu.

**Comment by adamgreen** [comment]
I have started getting the latest sources to run on my Bambino 210E board. I have it starting up now but I am hitting some issues in the code which I need to ping @arthurwolf about during his awake hours.

**Comment by kasandell** [comment]
All right sounds good. I've been trying to see if any of the fixes mentioned in  #13 work for the Bambino 210E. No luck so far.

**Comment by adamgreen** [comment]
@kasandell I should be ready to push up Bambino210E support on Tuesday afternoon. I just have a few more things to cleanup and discuss with Arthur before I do.

**Comment by kasandell** [comment]
Awesome. Thank you!

**Comment by adamgreen** [comment]
@kasandell I have updated the makefile to allow the Smoothie firmware to startup and run on my Bambino210E board. By default the makefile still builds a binary suitable for running on Smoothie2 boards but you can modify one line in the makefile to switch it to the Bambino210E. I documented the selection that you can select in the makefile [here](https://github.com/Smoothieware/Smoothie2/blob/fcf57d7d88717bd8a88669cdfd92059037323724/src/makefile#L13). That should allow you to see the output on the virtual serial port you get when you plug a USB cable into the **USB1** port on the board.

**Comment by adamgreen** [comment]
This should be fixed by PR #16. Please re-activate if not the case.
