### ISSUE TITLE
Bambino Disconnecting Serial Communication

### ISSUE THREAD

**Issue by kasandell** [Smoothieware/Smoothie2#17]
So I got the new source to compile and run, and I noticed that more often than not the Bambino will connect to my computer and show up under /dev/ and then after anywhere from 10-25 seconds, it will disappear from /dev/. When it does this, none of the serial communication applications can connect to it. I had added a few printfs() to the source, so I removed those thinking they might have been causing the issues somehow. Removing these did nothing, so I tried recloning the whole repo and starting from scratch, with no result. The board used to connect successfully and hold a serial communication line one out of every few tries, but now it fails on every try. I've tried switching USB cables, switching USB ports, flashing different file formats (Hex and bin), and don't know where to go from here. Also, when using a simple application(like blinking the lights on the board), the board stays connected to the computer, so I'm pretty sure it isn't an issue on my computer.

**Comment by arthurwolf** [comment]
Unfortunately, right now, you and @chrisbrent are being pioneers of Smoothie2+bambino. 
I don't have a bambino ( I should probably order one so I can be more helpful to you guys ).

@adamgreen mentionned getting MRI to work with Smoothie2. I believe that'd help debug this sort of situation ( though it could maybe require you also connect to another serial port with something like a FTDI cable ? )

**Comment by kasandell** [comment]
Alright. I'll see what I can do.

**Comment by chrisbrent** [comment]
@kasandell Are you using the virtual serial port on the usb port? I haven't tried that yet but will do so this afternoon. I've noticed that there are a few things that make Smoothie2 crash. e.g I can send ? and get back the GRBL style status, or M114 for the current position or set a tool offset with G10 X1, but if I send something like G1 BLAH Smoothie stops responding. I'm guessing something is crashing or failing that hasn't been ported yet. Setting up MRI would be useful, I'll try and do that today.

**Comment by kasandell** [comment]
@chrisbrent I actually did notice that G1 crashes Smoothie and that is what I was adding all the printf() statements for so I could see what was crashing it. And I do believe I am using the virtual serial port on USB1. I'll see what I can get from MRI.

**Comment by arthurwolf** [comment]
Oh ? G1 doesn't crash here, I tested step generation and stuf. Maybe
something related to the bambino.

On Tue, Jun 28, 2016 at 10:28 PM, Kyle Sandell notifications@github.com
wrote:

> @chrisbrent https://github.com/chrisbrent I actually did notice that G1
> crashes Smoothie and that is what I was adding all the printf() statements
> for so I could see what was crashing it. And I do believe I am using the
> virtual serial port on USB1. I'll see what I can get from MRI.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Smoothieware/Smoothie2/issues/17#issuecomment-229172652,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAGpFfw66ikGZuQmJ3-Svj4E0y2ffy_Zks5qQYPxgaJpZM4JAd2T
> .

## 

Courage et bonne humeur.

**Comment by kasandell** [comment]
Could be. Honestly wouldn't surprise me if it were bambino related. If I get this to work again I'll see what I can do about figuring out what's up with G1.

**Comment by arthurwolf** [comment]
I ordered a bambino and asked logxen to send the one I lent him back.
Hopefully I can help soon.

On Tue, Jun 28, 2016 at 10:33 PM, Kyle Sandell notifications@github.com
wrote:

> Could be. Honestly wouldn't surprise me if it were bambino related. If I
> get this to work again I'll see what I can do about figuring out what's up
> with G1.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Smoothieware/Smoothie2/issues/17#issuecomment-229174119,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAGpFVWHXYcX8rkKnrvzGNky8Eq9xFY4ks5qQYUUgaJpZM4JAd2T
> .

## 

Courage et bonne humeur.

**Comment by adamgreen** [comment]
This doesn't sound like a Smoothie firmware issue. It sounds like an issue with your serial hardware.

I should mention that I had some issues with the Bambino210E board while I was testing the build yesterday. I was initially using the CMSIS-DAP debugger via pyOCD to debug it. This is supported by the same mbed HDK chip on the Bambino210E which provided the virtual USB to serial port connection. When running the Smoothie firmware on my Bambino210E, I would hit weird issues where some pages of the FLASH would get deleted out from under me while I was debugging. In the end, my MacBook Air wouldn't even mount the USB device (Mass storage, virtual serial port, or CMSIS-DAP debugging interface). To correct the issue, I updated the firmware in the mbed HDK interface chip to only provide the virtual serial port and that made things much more reliable. You can find instructions on doing that here: http://wiki.micromint.com/index.php/Bambino-210_Manual/Appendix_B

**Comment by kasandell** [comment]
Hey @adamgreen so I've been trying to only provide the virtual serial port, but now when I plug in the board, whether or not I have JP3 shorted, the board comes up as CRP DISABLD instead of MBED. I did some research and found this https://www.lpcware.com/content/forum/exit-isp, which says that the bin file has an invalid CRC, so I tried reloading the original bambino hdk, with no luck. Did you experience anything similar?

**Comment by adamgreen** [comment]
@kasandell I had much more success with the Bambino210E after I switched out the interface firmware to just run the version which only supports the virtual serial port. You can find that image [here](http://www.micromint.com/updates/bambino/210/lpc11u35_vcom.bin) It sounds like you only need that functionality anyway so you should have no issue making that switch as well.

**Comment by kasandell** [comment]
@adamgreen the problem is in switching the interface firmware. I followed the instructions on switching and now my Bambino always comes up in disabled mode, and no longer as MBED. According to the website I listed above there's something wrong with the checksum. Did you have any issues with switching the interface firmware?

**Comment by adamgreen** [comment]
@kasandell I only tried the image I linked to in my previous comment. On OS X, I used the Terminal to perform the copy as I usually have better luck using a **cp** command in the Terminal than I do using the Finder for those foolish USB mass storage firmware updaters. Probably best to issue a **sync** command too after the **cp** command and before disconnecting the USB cable to make sure that all writes have been flushed. Once that is done, you will get a serial port but it won't show up as a USB drive at all anymore.

**Comment by kasandell** [comment]
Okay. I actually managed to do drag and drop on my Windows computer and it worked fine. It no longer shows up as a drive, so now I need to go figure out why Smoothie doesn't want to run.

**Comment by adamgreen** [comment]
With that new serial port only interface firmware, is the serial port still randomly disconnecting or is it now staying connected and you are just hitting some other issue with Smoothie?

**Comment by kasandell** [comment]
It's staying connected. Smoothie just doesn't send anything to signal that it's connected. I played with the makefile a bit so I'm going to revert those changes and see if it helps.

**Comment by adamgreen** [comment]
The only change you should need to make to the latest makefile is what I flag [here](https://github.com/Smoothieware/Smoothie2/blob/master/notes/Bambino210E-board.creole#building).  With that change, it works on my Bambino210E board.

**Comment by kasandell** [comment]
Yeah but when trying to diagnose this I was trying to get MRI working to see if it would help, and it looked like I had to add a flag or two to the makefile.

**Comment by adamgreen** [comment]
Closing this issue as you are no longer having the serial disconnect issue.

**Comment by adamgreen** [comment]
I should have instructions written up on using MRI with the Bambino210E and Smoothie2 boards later this week. I will probably make updates to the makefile to make it easier to use as well. 

You will need a usb to serial adapter to hook up to a secondary UART on the Arduino header pins of the Bambino210E board to make use of MRI though.

**Comment by adamgreen** [comment]
@kasandell I have added documentation about using MRI with the Bambino210E [here](https://github.com/Smoothieware/Smoothie2/blob/master/notes/Bambino210E-board.creole#debugging-with-mri). The MRI functionality was actually broken in the Smoothie tree until my latest changes.

**Comment by kasandell** [comment]
@adamgreen Sounds good. Currently looking into why G1 is broken on the Bambino, so hopefully MRI will help.
