### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by bsh314** [Smoothieware/Smoothie2#37]
There is no updates on blog nor this repo December 2016. 
I'm very scared that Smoothieboard 2 never gonna see the sunlight.

**Comment by arthurwolf** [comment]
The prototype for the v2-alpha board is being manufactured at the factory right now, and two persons are being paid to work on the low level code for the firmware. So this is very much alive, it's just such an enormous project it's taking a lot of time, and right now it's in a phase where most of the work is quiet from the public's perspective.

**Comment by bsh314** [comment]
Thanks for the quick reply! Great news!
